### ISSUE TITLE
Error in convert caffe model to pytorch version

### ISSUE THREAD

**Issue by zhijiew** [kazuto1011/pspnet-pytorch#1]
Hi, thanks for your nice work! I'm using your code but get some error in model transform, these are my error info:
**********************************
conv5_3_pool6_conv/bn     -> ppm.stages.0.conv.bn.weight : Copied
conv5_3_pool6_conv/bn     -> ppm.stages.0.conv.bn.running_var : Copied
conv5_3_pool6_conv/bn     -> ppm.stages.0.conv.bn.bias : Copied
conv5_3_pool6_conv/bn     -> ppm.stages.0.conv.bn.running_mean : Copied
conv5_4                   -> final.conv5_4.conv.weight : Copied
conv5_4/bn                -> final.conv5_4.bn.weight : Copied
conv5_4/bn                -> final.conv5_4.bn.running_var : Copied
conv5_4/bn                -> final.conv5_4.bn.bias : Copied
conv5_4/bn                -> final.conv5_4.bn.running_mean : Copied
conv6                     -> final.conv6.weight : Copied
conv6                     -> final.conv6.bias : Copied
conv4_24                  -> aux.conv4_aux.conv.weight : Copied
conv4_24/bn               -> aux.conv4_aux.bn.weight : Copied
conv4_24/bn               -> aux.conv4_aux.bn.running_var : Copied
conv4_24/bn               -> aux.conv4_aux.bn.bias : Copied
conv4_24/bn               -> aux.conv4_aux.bn.running_mean : Copied
Traceback (most recent call last):
  File "convert.py", line 168, in <module>
    main()
  File "/home/wzj/opt/miniconda2/envs/seg/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/wzj/opt/miniconda2/envs/seg/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/wzj/opt/miniconda2/envs/seg/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wzj/opt/miniconda2/envs/seg/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "convert.py", line 157, in main
    values = values.view_as(own_state[param_name])
  File "/home/wzj/opt/miniconda2/envs/seg/lib/python2.7/site-packages/torch/tensor.py", line 198, in view_as
    return self.view(tensor.size())
RuntimeError: invalid argument 2: size '[21 x 256 x 3 x 3]' is invalid for input with 5376 elements at /pytorch/torch/lib/TH/THStorage.c:41
**********************************************
I'm using python3.5 and pytorch0.3.0

Could you please help me fix this, or just share the model file you have transformed, thanks alot!

**Comment by kazuto1011** [comment]
Thanks for reporting the bug. My last change of the ```libs/models/pspnet.py``` seems to have done bad things. I have fixed the last 1x1 convolution layers in the auxiliary branch, although copying this branch is not necessary for inference.
